version: '3.4'

services:
  falc-identity-admin:
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "bin/Debug/net8.0/Falc.Identity.Admin.dll" /seed'

  falc-identity-admin-api:
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  falc-identity-sts:
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
