version: '3.5'
services:
  falc-identity-admin:
    build:
      context: .
      dockerfile: src/Falc.Identity.Admin/Dockerfile
    container_name: falc-identityserver-admin
    environment:
      - 'ConnectionStrings__ConfigurationDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__AdminLogDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://falc.admin.local'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://falc.admin.local/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://falc.sts.local'
      - AdminConfiguration__RequireHttpsMetadata=false
      - 'IdentityServerData__Clients__0__ClientUri=https://falc.admin.local'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://falc.admin.local/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://falc.admin.local/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://falc.admin.local/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://falc.admin.local'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://falc.admin-api.local/swagger/oauth2-redirect.html'
      - 'Serilog__WriteTo__1__Args__connectionString=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    command: /seed
    depends_on:
      - falc-identity-sts
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'
    networks:
      - falc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.falc-identity-admin.rule=Host(`falc.admin.local`)"
      - "traefik.http.routers.falc-identity-admin.entrypoints=websecure"
      - "traefik.http.routers.falc-identity-admin.tls=true"
      - "traefik.http.routers.http-falc-identity-admin.rule=Host(`falc.admin.local`)"
      - "traefik.http.routers.http-falc-identity-admin.entrypoints=web"
      - "traefik.tags=falc"
      - "traefik.docker.network=falc"

  falc-identity-admin-api:
    build:
      context: .
      dockerfile: src/Falc.Identity.Admin.Api/Dockerfile
    container_name: falc-identityserver-admin-api
    environment:
      - 'ConnectionStrings__ConfigurationDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__AdminLogDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - AdminApiConfiguration__RequireHttpsMetadata=false
      - 'AdminApiConfiguration__ApiBaseUrl=https://falc.admin-api.local'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://falc.sts.local'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - './shared/serilog.json:/app/serilog.json'
    networks:
      - falc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.falc-identity-admin-api.rule=Host(`falc.admin-api.local`)"
      - "traefik.http.routers.falc-identity-admin-api.entrypoints=websecure"
      - "traefik.http.routers.falc-identity-admin-api.tls=true"
      - "traefik.http.routers.http-falc-identity-admin-api.rule=Host(`falc.admin-api.local`)"
      - "traefik.http.routers.http-falc-identity-admin-api.entrypoints=web"
      - "traefik.tags=falc"
      - "traefik.docker.network=falc"

  falc-identity-sts:
    build:
      context: .
      dockerfile: src/Falc.Identity.STS.Identity/Dockerfile
    container_name: falc-identityserver-sts-identity
    environment:
      - 'ConnectionStrings__ConfigurationDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__IdentityDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Host=postgres;Username=postgres;Password=password;Database=Falc.Identity;Include Error Detail=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://falc.admin.local'
      - 'AdvancedConfiguration__IssuerUri=https://falc.sts.local'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - './shared/serilog.json:/app/serilog.json'
    networks:
      - falc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.falc-identity-sts.rule=Host(`falc.sts.local`)"
      - "traefik.http.routers.falc-identity-sts.entrypoints=websecure"
      - "traefik.http.routers.falc-identity-sts.tls=true"
      - "traefik.http.routers.http-falc-identity-sts.rule=Host(`falc.sts.local`)"
      - "traefik.http.routers.http-falc-identity-sts.entrypoints=web"
      - "traefik.tags=falc"
      - "traefik.docker.network=falc"

networks:
  falc:
    external: true
